IT4Change/boilerplate-frontend

.github/file-filters.yml, .github/workflows/test.lint.code.yml, .github/workflows/test.lint.pr.yml, .github/workflows/test.unit.code.yml
=> feat(workflow): test:unit workflow

.github/file-filters.yml, .github/workflows/test.build.code.yml, .github/workflows/test.lint.code.yml, .github/workflows/test.lint.pr.yml, .github/workflows/test.unit.code.yml, README.md, package.json, vitest.config.ts
=> feat(workflow): build test workflow

.github/file-filters.yml, .github/workflows/deploy.docs.yml, .github/workflows/test.build.docs.yml, .github/workflows/test.lint.pr.yml, README.md
deploy docs to github - workflow
- None
=> feat(workflow): deploy docs to github - workflow

.eslintrc.json, .github/file-filters.yml, .github/workflows/frontend.deploy.docs.yml, .vuepress/config.ts, renderer/i18n.ts
=> fix(workflow): lint & docu fixes

.github/workflows/frontend.deploy.chromatic.yml, .gitignore, README.md, package-lock.json, package.json
=> feat(frontend): chromatic + workflow

README.md
=> docs(frontend): chromatic readme

src/components/PageShell.vue, src/layouts/DefaultLayout.vue
=> feat(frontend): switch TopBar from DefaultLayout to PageShell

README.md, src/components/ClientOnly.vue, src/locales/de.json
Just cleanup some things
- None
=> fix(frontend): cleanup

README.md
document how to update the subtree
- None
=> fix(docu): document how to update the subtree

.github/workflows/frontend.deploy.docs.yml, .vuepress/config.ts
=> fix(workflow): docs base configurable

.github/workflows/frontend.deploy.docs.yml, .vuepress/config.ts
Ensure `VUEPRESS_BASE` is surrounded by slashes. Consequently we meet the typecheck, but require the base to be defined without trailing slashes.
- None
=> fix(docu): fix type error vuepress base

src/stores/counter.test.ts
Adds a unit test to the store
- None
=> feat(frontend): test store

.eslintignore, .eslintrc.json, package.json, renderer/_default.page.client.ts, renderer/app.ts, renderer/plugins/vuetify.ts, server/index.ts, src/components/ClientOnly.test.ts, src/env.ts, src/pages/_error.page.test.ts, src/pages/app/index.page.server.ts, src/stores/counter.test.ts, src/stories/ExampleHeader.stories.ts, src/stories/ExamplePage.stories.ts, types/vue.d.ts
eslint typescript strict
- None
=> fix(other): eslint typescript strict

package-lock.json, package.json, renderer/app.ts, src/stories/ExampleButton.stories.ts, src/stories/ExampleHeader.stories.ts, src/stories/ExamplePage.stories.ts, types/Component.ts, types/vue.d.ts, vite.config.ts
typechecks & type cleanups
- None
=> feat(frontend): typechecks & type cleanups

package.json, server/index.ts, src/stories/ExampleButton.stories.ts, src/stories/ExampleHeader.stories.ts, src/stories/ExamplePage.stories.ts, tsconfig.json, types/SBComp.ts, vite.config.ts
- import order supports the developer
- SBComp for StoryBook Typings
- Some more type and warning fixes
- None
=> refactor(frontend): import order + sbcomp + some types

.github/dependabot.yml
=> chore(workflow): dependabot support

renderer/+onHydrationEnd.ts, renderer/+onPageTransitionEnd.ts, renderer/+onPageTransitionStart.ts
deleted unused debug handlers
- None
=> fix(frontend): deleted unused debug handlers

renderer/context/usePageContext.ts, src/components/VikeBtn.test.ts, src/components/VikeBtn.vue
utilize vike navigate for client side navigation
- None
=> feat(frontend): utilize vike-navigate

renderer/app.ts, renderer/context/usePageContext.ts, src/components/VikeBtn.test.ts, vitest.config.ts
=> feat(frontend): test vike button

README.md
=> docs(frontend): fix readme

.vuepress/config.ts, package-lock.json, package.json
=> chore(docu): update vuepress

.github/file-filters.yml, .github/workflows/frontend.test.build.docker.yml, Dockerfile
=> fix(docker): docker rework

docker-compose.override.yml, docker-compose.yml
adjust docker files according to new insights
- None
=> fix(frontend): docker fixes

.github/dependabot.yml
=> refactor(frontend): fix dependabot pr limit problem

package-lock.json, package.json
=> chore(frontend): update packages 07 04

.github/workflows/frontend.deploy.docs.yml
=> refactor(frontend): use our vuepress deployment action in docs deployment workflow

.github/dependabot.yml
=> refactor(frontend): dependabot group updates

.github/dependabot.yml
=> refactor(frontend): refine dependabot groups

package-lock.json, package.json
Removes a dependency (https://www.npmjs.com/package/@vue/compiler-sfc) which was included in the main `vue` package.
- None
=> chore(frontend): remove unused dependency

.github/dependabot.yml
=> ci(other): refine dependabot eslint group

.github/file-filters.yml, .github/workflows/frontend.deploy.docs.yml
=> ci(workflow): refine deploy docs workflow

.github/dependabot.yml
=> refactor(other): refine dependabot vite package grouping
